version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - npm install
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 654654262271.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ws/assignment .
      - docker tag ws/assignment:latest 654654262271.dkr.ecr.ap-south-1.amazonaws.com/ws/assignment:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 654654262271.dkr.ecr.ap-south-1.amazonaws.com/ws/assignment:latest

artifacts:
  files:
    - "**/*"